### ISSUE TITLE
MultiPolygon not supported

### ISSUE THREAD

**Issue by goors** [maxogden/simplify-geojson#12]
As far as I can see from this:

```
module.exports = function (geojson, tolerance, dontClone) {
  if (!dontClone) geojson = JSON.parse(JSON.stringify(geojson)) // clone obj
  if (geojson.features) return simplifyFeatureCollection(geojson, tolerance)
  else if (geojson.type && geojson.type === 'Feature') return simplifyFeature(geojson, tolerance)
  else return new Error('FeatureCollection or individual Feature required')
}
```

MultiPolygon is not supported. Can you tell me why maybe?
I did npm install.

**Comment by ungoldman** [comment]
I think it was never implemented, and no one has asked for this feature or offered to contribute since.

If you're interested in adding this feature, you're welcome to try.

There may be a reason we didn't implement multipolygons, but it's been a few years since I've worked on this so I honestly can't say if a reason existed or not.
